export const GENERIC_MODAL_DEFAULT_ANIM_DURATION = 175;
export const GENERIC_MODAL_DEFAULT_INTERNAL_ANIM_DURATION = 350;

export const GENERIC_MODAL_DEFAULT_ANIM_DURATION_MULTIPLIER_SMALL = 0.65;
export const GENERIC_MODAL_DEFAULT_ANIM_DURATION_MULTIPLIER_LARGE = 0.85;